name: Deploy to FTP

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2

      - name: Install dependencies and build Next.js app
        run: |
          npm install  # Install project dependencies
          touch .env.local
          echo NEXT_PUBLIC_STRAPI_API_URL=${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }} >> .env.local
          echo NEXT_PUBLIC_STRAPI_API_TOKEN=${{ secrets.NEXT_PUBLIC_STRAPI_API_TOKEN }} >> .env.local
          npm run build  # Build Next.js app

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_TEST }}
          username: ${{ secrets.FTP_USERNAME_TEST }}
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          local-dir: ./
          server-dir: /
          protocol: ftps
          timeout: 300000 # Set a longer timeout value in milliseconds (here, 2 minutes)
